package segment

import (
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// updateGolden regenerates testdata/golden_block.bin from the
// hand-pinned event list below. Reviewers see the regenerated bytes
// as a diff in the PR and approve format changes deliberately.
var updateGolden = flag.Bool("update", false, "regenerate golden testdata")

// goldenEvents is the deterministic input for the golden fixture.
// Do NOT change without intentionally breaking the wire format.
func goldenEvents() []Event {
	return []Event{
		{
			Seq: 1, WitnessedAt: 1700000000_000000, IndexedAt: 0,
			Kind:       KindCreate,
			DID:        "did:plc:abcdefghijklmnopqrstuvwx",
			Collection: "app.bsky.feed.post",
			Rkey:       "3l3qo2vuowo2b",
			Rev:        "3l3qo2vutsw2b",
			Payload:    []byte{0xA1, 0x65, 0x68, 0x65, 0x6C, 0x6C, 0x6F, 0x05},
		},
		{
			Seq: 2, WitnessedAt: 1700000001_000000, IndexedAt: 1700000000_500000,
			Kind: KindIdentity,
			DID:  "did:web:example.com",
		},
		{
			Seq: 3, WitnessedAt: 1700000002_000000, IndexedAt: 0,
			Kind:       KindDelete,
			DID:        "did:plc:zzzzzzzzzzzzzzzzzzzzzzzz",
			Collection: "app.bsky.feed.like",
			Rkey:       "3l3qo2vuowo2c",
			Rev:        "3l3qo2vutsw2c",
		},
	}
}

func TestGolden(t *testing.T) { //nolint:paralleltest
	// We deliberately do not t.Parallel: when -update is set this
	// writes a file other tests in the package might race against.

	encoded, err := encodeBlockCompressed(goldenEvents())
	require.NoError(t, err)

	path := filepath.Join("testdata", "golden_block.bin")

	if *updateGolden {
		require.NoError(t, os.MkdirAll("testdata", 0o755))
		require.NoError(t, os.WriteFile(path, encoded, 0o644))
		t.Logf("wrote %d bytes to %s", len(encoded), path)
		return
	}

	want, err := os.ReadFile(path)
	require.NoError(t, err,
		"golden missing; regenerate with: go test ./segment -run TestGolden -update")
	require.Equal(t, want, encoded,
		"wire format drift; if intentional, regenerate with: "+
			"go test ./segment -run TestGolden -update")
}
