package segment

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestRewriteRightSizesBloomsToSurvivingCardinality pins issue #303:
// Rewrite must recompute per-block bloom params from the surviving
// rows rather than pinning the source segment's params. A segment
// whose bloom size was driven by one DID-dense block must shrink its
// blooms when a rewrite drops that block's rows.
func TestRewriteRightSizesBloomsToSurvivingCardinality(t *testing.T) {
	t.Parallel()

	// Block 0: 2 unique DIDs. Block 1: 256 distinct DIDs (drives the
	// segment-wide bloom capacity under #302's max rule).
	var events []Event
	seq := uint64(0)
	for i := range 32 {
		seq++
		events = append(events, Event{
			Seq: seq, WitnessedAt: int64(seq), Kind: KindCreate,
			DID:        fmt.Sprintf("did:plc:sparse%d", i%2),
			Collection: "app.bsky.feed.post",
			Rkey:       fmt.Sprintf("k%d", seq), Rev: "v", Payload: []byte("p"),
		})
	}
	for i := range 256 {
		seq++
		events = append(events, Event{
			Seq: seq, WitnessedAt: int64(seq), Kind: KindCreate,
			DID:        fmt.Sprintf("did:plc:dense%04d", i),
			Collection: "app.bsky.feed.post",
			Rkey:       fmt.Sprintf("k%d", seq), Rev: "v", Payload: []byte("p"),
		})
	}

	path := filepath.Join(t.TempDir(), "seg.jss")
	w, err := New(Config{Path: path})
	require.NoError(t, err)
	for i, ev := range events {
		_, err := w.Append(ev)
		require.NoError(t, err)
		if i == 31 { // block break between sparse and dense
			require.NoError(t, w.Flush())
		}
	}
	_, err = w.Seal()
	require.NoError(t, err)

	insBefore, err := Inspect(path)
	require.NoError(t, err)
	require.Len(t, insBefore.Blocks, 2)

	// Drop every dense-block row; only the 2 sparse DIDs survive.
	res, err := Rewrite(path, func(ev *Event) RowDecision {
		if len(ev.DID) > len("did:plc:dense") && ev.DID[:13] == "did:plc:dense" {
			return RowDrop
		}
		return RowKeep
	}, RewriteOptions{})
	require.NoError(t, err)
	require.True(t, res.Rewritten)
	require.EqualValues(t, 256, res.RowsDropped)

	insAfter, err := Inspect(path)
	require.NoError(t, err)
	require.True(t, insAfter.ChecksumValid)

	// Surviving max cardinality is 2; params pinned from the source
	// would keep the capacity-256 size. Require a real shrink.
	require.Lessf(t, insAfter.PerBlockBloomBytes, insBefore.PerBlockBloomBytes,
		"rewrite pinned source bloom params: %d bytes before, %d after",
		insBefore.PerBlockBloomBytes, insAfter.PerBlockBloomBytes)
	require.Lessf(t, insAfter.PerBlockBloomBytes, uint32(300),
		"blooms not right-sized for 2 surviving DIDs: %d bytes",
		insAfter.PerBlockBloomBytes)

	// One-sided contract intact for every surviving DID.
	r, err := Open(ReaderConfig{Path: path})
	require.NoError(t, err)
	t.Cleanup(func() { _ = r.Close() })
	for i := range 2 {
		sel, err := r.BlocksContainingDID(fmt.Sprintf("did:plc:sparse%d", i))
		require.NoError(t, err)
		require.Containsf(t, sel, 0, "surviving DID sparse%d lost from block 0", i)
	}
	require.NoError(t, VerifySealedMetadata(r))
}

// TestRewriteShrinksLegacyFixedCapacityBlooms pins the production
// migration path for #303: rewriting a segment sealed by pre-#302
// code (fixed capacity-4096 blooms, 8,409 bytes each) must emit
// right-sized blooms. The fixture was generated by the pre-#302 seal
// path (see testdata/README note in the fixture's commit); its blocks
// hold 2 and 1 unique DIDs respectively.
func TestRewriteShrinksLegacyFixedCapacityBlooms(t *testing.T) {
	t.Parallel()

	src, err := os.ReadFile(filepath.Join("testdata", "legacy_fixed4096_blooms.jss"))
	require.NoError(t, err)
	path := filepath.Join(t.TempDir(), "seg.jss")
	require.NoError(t, os.WriteFile(path, src, 0o644))

	insBefore, err := Inspect(path)
	require.NoError(t, err)
	require.True(t, insBefore.ChecksumValid)
	require.EqualValues(t, 8409, insBefore.PerBlockBloomBytes,
		"fixture no longer carries legacy fixed-capacity blooms; regenerate from pre-#302 code")

	// Drop one row so the rewrite actually runs (Rewrite early-returns
	// when nothing is dropped — legacy blooms shrink only when
	// compaction touches the segment, by design).
	dropped := false
	res, err := Rewrite(path, func(ev *Event) RowDecision {
		if !dropped && ev.DID == "did:plc:legacy-b0-u1" {
			dropped = true
			return RowDrop
		}
		return RowKeep
	}, RewriteOptions{})
	require.NoError(t, err)
	require.True(t, res.Rewritten)
	require.EqualValues(t, 1, res.RowsDropped)

	insAfter, err := Inspect(path)
	require.NoError(t, err)
	require.True(t, insAfter.ChecksumValid)
	require.Lessf(t, insAfter.PerBlockBloomBytes, uint32(300),
		"legacy blooms not right-sized by rewrite: %d bytes (was 8409)",
		insAfter.PerBlockBloomBytes)

	// Every surviving DID still selects its block; full metadata check.
	r, err := Open(ReaderConfig{Path: path})
	require.NoError(t, err)
	t.Cleanup(func() { _ = r.Close() })
	for _, did := range []string{"did:plc:legacy-b0-u0", "did:plc:legacy-b0-u1", "did:plc:legacy-b1-u0"} {
		// b0-u1 still has rows left (only one of its rows was dropped).
		sel, err := r.BlocksContainingDID(did)
		require.NoError(t, err)
		require.NotEmptyf(t, sel, "surviving DID %s lost from selection", did)
	}
	require.NoError(t, VerifySealedMetadata(r))
}
