// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"encoding/json"
	"fmt"
	lextypes "github.com/bluesky-social/jetstream/api/lextypes"
	comatproto "github.com/jcalabro/atmos/api/comatproto"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/gt"
)

// JetstreamSubscribeEvents_Account is a "account" in the network.bsky.jetstream.subscribeEvents schema.
//
// An account status change (active/deactivated/deleted/...), wrapping the upstream firehose event verbatim.
type JetstreamSubscribeEvents_Account struct {
	LexiconTypeID string                                `json:"$type,omitempty"`
	Account       comatproto.SyncSubscribeRepos_Account `json:"account"` // The upstream event; its seq and time are the upstream relay's, not Jetstream's.
	DID           string                                `json:"did"`
	Seq           int64                                 `json:"seq"`
	Time          string                                `json:"time"` // The time Jetstream witnessed this event, microsecond precision. Timestamp imports apply only to r...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamSubscribeEvents_Account.
var (
	cborKey_JetstreamSubscribeEvents_Account_did         = cbor.AppendTextKey(nil, "did")
	cborKey_JetstreamSubscribeEvents_Account_seq         = cbor.AppendTextKey(nil, "seq")
	cborKey_JetstreamSubscribeEvents_Account_time        = cbor.AppendTextKey(nil, "time")
	cborKey_JetstreamSubscribeEvents_Account_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamSubscribeEvents_Account_account     = cbor.AppendTextKey(nil, "account")
)

func (s *JetstreamSubscribeEvents_Account) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Account) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "seq", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "time", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_time...)
		buf = cbor.AppendText(buf, s.Time)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "account", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_account...)
		{
			var err error
			buf, err = s.Account.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_time...)
		buf = cbor.AppendText(buf, s.Time)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Account_account...)
		{
			var err error
			buf, err = s.Account.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Account) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Account) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "seq" {
				s.Seq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "time" {
				s.Time, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "account" {
				pos, err = s.Account.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamSubscribeEvents_Account.
var (
	jsonKey_JetstreamSubscribeEvents_Account_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamSubscribeEvents_Account_account     = []byte("\"account\":")
	jsonKey_JetstreamSubscribeEvents_Account_did         = []byte("\"did\":")
	jsonKey_JetstreamSubscribeEvents_Account_seq         = []byte("\"seq\":")
	jsonKey_JetstreamSubscribeEvents_Account_time        = []byte("\"time\":")
)

func (s *JetstreamSubscribeEvents_Account) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Account) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Account_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Account_account...)
	{
		var err error
		buf, err = s.Account.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Account_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Account_seq...)
	buf = cbor.AppendJSONInt(buf, s.Seq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Account_time...)
	buf = cbor.AppendJSONString(buf, s.Time)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Account) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Account) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "account":
			pos, err = s.Account.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "seq":
			s.Seq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "time":
			s.Time, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamSubscribeEvents_Commit is a "commit" in the network.bsky.jetstream.subscribeEvents schema.
//
// A single record mutation (create, update, or delete).
type JetstreamSubscribeEvents_Commit struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	CID           gt.Option[string] `json:"cid,omitzero"` // CID of the record. Absent for deletes.
	Collection    string            `json:"collection"`   // Collection NSID of the record.
	DID           string            `json:"did"`
	Operation     string            `json:"operation"`
	Record        json.RawMessage   `json:"record,omitempty"` // The record decoded to JSON. Absent for deletes.
	Rev           string            `json:"rev"`              // The repo rev of the commit that produced this op.
	Rkey          string            `json:"rkey"`             // Record key.
	Seq           int64             `json:"seq"`              // Jetstream's monotonic per-event sequence number; the stream cursor.
	Time          string            `json:"time"`             // The event's display timestamp, microsecond precision: when Jetstream witnessed the event, unless ...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamSubscribeEvents_Commit.
var (
	cborKey_JetstreamSubscribeEvents_Commit_cid         = cbor.AppendTextKey(nil, "cid")
	cborKey_JetstreamSubscribeEvents_Commit_did         = cbor.AppendTextKey(nil, "did")
	cborKey_JetstreamSubscribeEvents_Commit_rev         = cbor.AppendTextKey(nil, "rev")
	cborKey_JetstreamSubscribeEvents_Commit_seq         = cbor.AppendTextKey(nil, "seq")
	cborKey_JetstreamSubscribeEvents_Commit_rkey        = cbor.AppendTextKey(nil, "rkey")
	cborKey_JetstreamSubscribeEvents_Commit_time        = cbor.AppendTextKey(nil, "time")
	cborKey_JetstreamSubscribeEvents_Commit_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamSubscribeEvents_Commit_record      = cbor.AppendTextKey(nil, "record")
	cborKey_JetstreamSubscribeEvents_Commit_operation   = cbor.AppendTextKey(nil, "operation")
	cborKey_JetstreamSubscribeEvents_Commit_collection  = cbor.AppendTextKey(nil, "collection")
)

func (s *JetstreamSubscribeEvents_Commit) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Commit) AppendCBOR(buf []byte) ([]byte, error) {
	n := 7 + countExtra(s.extra, extraEncodingCBOR)
	if s.CID.HasVal() {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Record != nil {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "cid", buf)
		if s.CID.HasVal() {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_cid...)
			buf = cbor.AppendText(buf, s.CID.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rev", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_rev...)
		buf = cbor.AppendText(buf, s.Rev)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "seq", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rkey", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_rkey...)
		buf = cbor.AppendText(buf, s.Rkey)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "time", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_time...)
		buf = cbor.AppendText(buf, s.Time)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "record", buf)
		if s.Record != nil {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_record...)
			buf = cbor.AppendNull(buf)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "operation", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_operation...)
		buf = cbor.AppendText(buf, s.Operation)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "collection", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_collection...)
		buf = cbor.AppendText(buf, s.Collection)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.CID.HasVal() {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_cid...)
			buf = cbor.AppendText(buf, s.CID.Val())
		}
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_rev...)
		buf = cbor.AppendText(buf, s.Rev)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_rkey...)
		buf = cbor.AppendText(buf, s.Rkey)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_time...)
		buf = cbor.AppendText(buf, s.Time)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Record != nil {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_record...)
			buf = cbor.AppendNull(buf)
		}
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_operation...)
		buf = cbor.AppendText(buf, s.Operation)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Commit_collection...)
		buf = cbor.AppendText(buf, s.Collection)
	}
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Commit) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Commit) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "cid" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.CID = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "rev" {
				s.Rev, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "seq" {
				s.Seq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "rkey" {
				s.Rkey, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "time" {
				s.Time, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "record" {
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "operation" {
				s.Operation, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "collection" {
				s.Collection, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamSubscribeEvents_Commit.
var (
	jsonKey_JetstreamSubscribeEvents_Commit_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamSubscribeEvents_Commit_cid         = []byte("\"cid\":")
	jsonKey_JetstreamSubscribeEvents_Commit_collection  = []byte("\"collection\":")
	jsonKey_JetstreamSubscribeEvents_Commit_did         = []byte("\"did\":")
	jsonKey_JetstreamSubscribeEvents_Commit_operation   = []byte("\"operation\":")
	jsonKey_JetstreamSubscribeEvents_Commit_record      = []byte("\"record\":")
	jsonKey_JetstreamSubscribeEvents_Commit_rev         = []byte("\"rev\":")
	jsonKey_JetstreamSubscribeEvents_Commit_rkey        = []byte("\"rkey\":")
	jsonKey_JetstreamSubscribeEvents_Commit_seq         = []byte("\"seq\":")
	jsonKey_JetstreamSubscribeEvents_Commit_time        = []byte("\"time\":")
)

func (s *JetstreamSubscribeEvents_Commit) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Commit) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.CID.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_cid...)
		buf = cbor.AppendJSONString(buf, s.CID.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_collection...)
	buf = cbor.AppendJSONString(buf, s.Collection)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_operation...)
	buf = cbor.AppendJSONString(buf, s.Operation)
	first = false
	if s.Record != nil {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_record...)
		buf = append(buf, s.Record...)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_rev...)
	buf = cbor.AppendJSONString(buf, s.Rev)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_rkey...)
	buf = cbor.AppendJSONString(buf, s.Rkey)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_seq...)
	buf = cbor.AppendJSONInt(buf, s.Seq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Commit_time...)
	buf = cbor.AppendJSONString(buf, s.Time)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Commit) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Commit) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cid":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.CID = gt.Some(v)
			}
		case "collection":
			s.Collection, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "operation":
			s.Operation, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "record":
			{
				start := pos
				pos, err = cbor.SkipJSONValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.Record = json.RawMessage(data[start:pos])
			}
		case "rev":
			s.Rev, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "rkey":
			s.Rkey, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "seq":
			s.Seq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "time":
			s.Time, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamSubscribeEvents_Identity is a "identity" in the network.bsky.jetstream.subscribeEvents schema.
//
// An identity change (handle or DID document update), wrapping the upstream firehose event verbatim.
type JetstreamSubscribeEvents_Identity struct {
	LexiconTypeID string                                 `json:"$type,omitempty"`
	DID           string                                 `json:"did"`
	Identity      comatproto.SyncSubscribeRepos_Identity `json:"identity"` // The upstream event; its seq and time are the upstream relay's, not Jetstream's.
	Seq           int64                                  `json:"seq"`
	Time          string                                 `json:"time"` // The time Jetstream witnessed this event, microsecond precision. Timestamp imports apply only to r...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamSubscribeEvents_Identity.
var (
	cborKey_JetstreamSubscribeEvents_Identity_did         = cbor.AppendTextKey(nil, "did")
	cborKey_JetstreamSubscribeEvents_Identity_seq         = cbor.AppendTextKey(nil, "seq")
	cborKey_JetstreamSubscribeEvents_Identity_time        = cbor.AppendTextKey(nil, "time")
	cborKey_JetstreamSubscribeEvents_Identity_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamSubscribeEvents_Identity_identity    = cbor.AppendTextKey(nil, "identity")
)

func (s *JetstreamSubscribeEvents_Identity) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Identity) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "seq", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "time", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_time...)
		buf = cbor.AppendText(buf, s.Time)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "identity", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_identity...)
		{
			var err error
			buf, err = s.Identity.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_time...)
		buf = cbor.AppendText(buf, s.Time)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Identity_identity...)
		{
			var err error
			buf, err = s.Identity.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Identity) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Identity) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "seq" {
				s.Seq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "time" {
				s.Time, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "identity" {
				pos, err = s.Identity.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamSubscribeEvents_Identity.
var (
	jsonKey_JetstreamSubscribeEvents_Identity_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamSubscribeEvents_Identity_did         = []byte("\"did\":")
	jsonKey_JetstreamSubscribeEvents_Identity_identity    = []byte("\"identity\":")
	jsonKey_JetstreamSubscribeEvents_Identity_seq         = []byte("\"seq\":")
	jsonKey_JetstreamSubscribeEvents_Identity_time        = []byte("\"time\":")
)

func (s *JetstreamSubscribeEvents_Identity) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Identity) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Identity_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Identity_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Identity_identity...)
	{
		var err error
		buf, err = s.Identity.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Identity_seq...)
	buf = cbor.AppendJSONInt(buf, s.Seq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Identity_time...)
	buf = cbor.AppendJSONString(buf, s.Time)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Identity) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Identity) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "identity":
			pos, err = s.Identity.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "seq":
			s.Seq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "time":
			s.Time, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamSubscribeEvents_Info is a "info" in the network.bsky.jetstream.subscribeEvents schema.
//
// An advisory, non-fatal notice about the stream (mirrors com.atproto.sync.subscribeRepos#info). Carries no seq and does not advance the cursor. OutdatedCursor is sent as the first frame when a unix-microseconds timestamp cursor below the retention floor was clamped up to the floor; the message names the seq actually resumed from.
type JetstreamSubscribeEvents_Info struct {
	LexiconTypeID string            `json:"$type,omitempty"`
	Message       gt.Option[string] `json:"message,omitzero"`
	Name          string            `json:"name"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamSubscribeEvents_Info.
var (
	cborKey_JetstreamSubscribeEvents_Info_name        = cbor.AppendTextKey(nil, "name")
	cborKey_JetstreamSubscribeEvents_Info_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamSubscribeEvents_Info_message     = cbor.AppendTextKey(nil, "message")
)

func (s *JetstreamSubscribeEvents_Info) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Info) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Message.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "name", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_name...)
		buf = cbor.AppendText(buf, s.Name)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "message", buf)
		if s.Message.HasVal() {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_message...)
			buf = cbor.AppendText(buf, s.Message.Val())
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_name...)
		buf = cbor.AppendText(buf, s.Name)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Message.HasVal() {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Info_message...)
			buf = cbor.AppendText(buf, s.Message.Val())
		}
	}
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Info) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Info) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "message" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Message = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamSubscribeEvents_Info.
var (
	jsonKey_JetstreamSubscribeEvents_Info_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamSubscribeEvents_Info_message     = []byte("\"message\":")
	jsonKey_JetstreamSubscribeEvents_Info_name        = []byte("\"name\":")
)

func (s *JetstreamSubscribeEvents_Info) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Info) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Info_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Message.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Info_message...)
		buf = cbor.AppendJSONString(buf, s.Message.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Info_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Info) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Info) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "message":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Message = gt.Some(v)
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamSubscribeEvents_Subprotocol is the stream's default wire subprotocol when a
// client does not negotiate one via Sec-WebSocket-Protocol.
const JetstreamSubscribeEvents_Subprotocol = "xrpc.v1.json"

// JetstreamSubscribeEvents_Message is a union type.
type JetstreamSubscribeEvents_Message struct {
	JetstreamSubscribeEvents_Commit   gt.Ref[JetstreamSubscribeEvents_Commit]
	JetstreamSubscribeEvents_Identity gt.Ref[JetstreamSubscribeEvents_Identity]
	JetstreamSubscribeEvents_Account  gt.Ref[JetstreamSubscribeEvents_Account]
	JetstreamSubscribeEvents_Sync     gt.Ref[JetstreamSubscribeEvents_Sync]
	JetstreamSubscribeEvents_Info     gt.Ref[JetstreamSubscribeEvents_Info]
	Unknown                           gt.Ref[lextypes.UnknownUnionVariant]
}

func (u JetstreamSubscribeEvents_Message) MarshalJSON() ([]byte, error) {
	return u.AppendJSON(make([]byte, 0, 256))
}

func (u JetstreamSubscribeEvents_Message) AppendJSON(buf []byte) ([]byte, error) {
	if u.JetstreamSubscribeEvents_Commit.HasVal() {
		v := *u.JetstreamSubscribeEvents_Commit.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#commit"
		return v.AppendJSON(buf)
	}
	if u.JetstreamSubscribeEvents_Identity.HasVal() {
		v := *u.JetstreamSubscribeEvents_Identity.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#identity"
		return v.AppendJSON(buf)
	}
	if u.JetstreamSubscribeEvents_Account.HasVal() {
		v := *u.JetstreamSubscribeEvents_Account.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#account"
		return v.AppendJSON(buf)
	}
	if u.JetstreamSubscribeEvents_Sync.HasVal() {
		v := *u.JetstreamSubscribeEvents_Sync.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#sync"
		return v.AppendJSON(buf)
	}
	if u.JetstreamSubscribeEvents_Info.HasVal() {
		v := *u.JetstreamSubscribeEvents_Info.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#info"
		return v.AppendJSON(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().Raw...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union JetstreamSubscribeEvents_Message")
}

func (u *JetstreamSubscribeEvents_Message) UnmarshalJSON(data []byte) error {
	_, err := u.UnmarshalJSONAt(data, 0)
	return err
}

func (u *JetstreamSubscribeEvents_Message) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	endPos, err := cbor.SkipJSONValue(data, pos)
	if err != nil {
		return 0, err
	}
	typ, err := cbor.PeekJSONType(data[pos:endPos])
	if err != nil {
		return 0, err
	}
	switch typ {
	case "network.bsky.jetstream.subscribeEvents#commit":
		var v JetstreamSubscribeEvents_Commit
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Commit = gt.SomeRef(v)
		return endPos, nil
	case "network.bsky.jetstream.subscribeEvents#identity":
		var v JetstreamSubscribeEvents_Identity
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Identity = gt.SomeRef(v)
		return endPos, nil
	case "network.bsky.jetstream.subscribeEvents#account":
		var v JetstreamSubscribeEvents_Account
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Account = gt.SomeRef(v)
		return endPos, nil
	case "network.bsky.jetstream.subscribeEvents#sync":
		var v JetstreamSubscribeEvents_Sync
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Sync = gt.SomeRef(v)
		return endPos, nil
	case "network.bsky.jetstream.subscribeEvents#info":
		var v JetstreamSubscribeEvents_Info
		endPos, err = v.UnmarshalJSONAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Info = gt.SomeRef(v)
		return endPos, nil
	default:
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, Raw: json.RawMessage(data[pos:endPos])})
		return endPos, nil
	}
}

func (u JetstreamSubscribeEvents_Message) MarshalCBOR() ([]byte, error) {
	return u.AppendCBOR(make([]byte, 0, 256))
}

func (u JetstreamSubscribeEvents_Message) AppendCBOR(buf []byte) ([]byte, error) {
	if u.JetstreamSubscribeEvents_Commit.HasVal() {
		v := *u.JetstreamSubscribeEvents_Commit.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#commit"
		return v.AppendCBOR(buf)
	}
	if u.JetstreamSubscribeEvents_Identity.HasVal() {
		v := *u.JetstreamSubscribeEvents_Identity.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#identity"
		return v.AppendCBOR(buf)
	}
	if u.JetstreamSubscribeEvents_Account.HasVal() {
		v := *u.JetstreamSubscribeEvents_Account.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#account"
		return v.AppendCBOR(buf)
	}
	if u.JetstreamSubscribeEvents_Sync.HasVal() {
		v := *u.JetstreamSubscribeEvents_Sync.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#sync"
		return v.AppendCBOR(buf)
	}
	if u.JetstreamSubscribeEvents_Info.HasVal() {
		v := *u.JetstreamSubscribeEvents_Info.Val()
		v.LexiconTypeID = "network.bsky.jetstream.subscribeEvents#info"
		return v.AppendCBOR(buf)
	}
	if u.Unknown.HasVal() {
		return append(buf, u.Unknown.Val().RawCBOR...), nil
	}
	return nil, fmt.Errorf("cannot marshal empty union JetstreamSubscribeEvents_Message")
}

func (u *JetstreamSubscribeEvents_Message) UnmarshalCBOR(data []byte) error {
	_, err := u.UnmarshalCBORAt(data, 0)
	return err
}

func (u *JetstreamSubscribeEvents_Message) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	typ, err := cbor.PeekTypeAt(data, pos)
	if err != nil {
		return 0, err
	}
	switch typ {
	case "network.bsky.jetstream.subscribeEvents#commit":
		var v JetstreamSubscribeEvents_Commit
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Commit = gt.SomeRef(v)
		return pos, nil
	case "network.bsky.jetstream.subscribeEvents#identity":
		var v JetstreamSubscribeEvents_Identity
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Identity = gt.SomeRef(v)
		return pos, nil
	case "network.bsky.jetstream.subscribeEvents#account":
		var v JetstreamSubscribeEvents_Account
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Account = gt.SomeRef(v)
		return pos, nil
	case "network.bsky.jetstream.subscribeEvents#sync":
		var v JetstreamSubscribeEvents_Sync
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Sync = gt.SomeRef(v)
		return pos, nil
	case "network.bsky.jetstream.subscribeEvents#info":
		var v JetstreamSubscribeEvents_Info
		pos, err = v.UnmarshalCBORAt(data, pos)
		if err != nil {
			return 0, err
		}
		u.JetstreamSubscribeEvents_Info = gt.SomeRef(v)
		return pos, nil
	default:
		startPos := pos
		pos, err = cbor.SkipValue(data, pos)
		if err != nil {
			return 0, err
		}
		raw := make([]byte, pos-startPos)
		copy(raw, data[startPos:pos])
		u.Unknown = gt.SomeRef(lextypes.UnknownUnionVariant{Type: typ, RawCBOR: raw})
		return pos, nil
	}
}

// JetstreamSubscribeEvents_Sync is a "sync" in the network.bsky.jetstream.subscribeEvents schema.
//
// An archived #sync event (broken commit chain; consumers should resync the repo), wrapping the upstream firehose event verbatim. Never emitted on the legacy v1 /subscribe wire.
type JetstreamSubscribeEvents_Sync struct {
	LexiconTypeID string                             `json:"$type,omitempty"`
	DID           string                             `json:"did"`
	Seq           int64                              `json:"seq"`
	Sync          comatproto.SyncSubscribeRepos_Sync `json:"sync"` // The upstream event; its seq and time are the upstream relay's, not Jetstream's.
	Time          string                             `json:"time"` // The time Jetstream witnessed this event, microsecond precision. Timestamp imports apply only to r...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamSubscribeEvents_Sync.
var (
	cborKey_JetstreamSubscribeEvents_Sync_did         = cbor.AppendTextKey(nil, "did")
	cborKey_JetstreamSubscribeEvents_Sync_seq         = cbor.AppendTextKey(nil, "seq")
	cborKey_JetstreamSubscribeEvents_Sync_sync        = cbor.AppendTextKey(nil, "sync")
	cborKey_JetstreamSubscribeEvents_Sync_time        = cbor.AppendTextKey(nil, "time")
	cborKey_JetstreamSubscribeEvents_Sync_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *JetstreamSubscribeEvents_Sync) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Sync) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "did", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_did...)
		buf = cbor.AppendText(buf, s.DID)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "seq", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "sync", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_sync...)
		{
			var err error
			buf, err = s.Sync.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "time", buf)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_time...)
		buf = cbor.AppendText(buf, s.Time)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_did...)
		buf = cbor.AppendText(buf, s.DID)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_seq...)
		buf = cbor.AppendInt(buf, s.Seq)
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_sync...)
		{
			var err error
			buf, err = s.Sync.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_time...)
		buf = cbor.AppendText(buf, s.Time)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamSubscribeEvents_Sync_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Sync) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Sync) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "did" {
				s.DID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "seq" {
				s.Seq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 4:
			if string(data[keyStart:keyEnd]) == "sync" {
				pos, err = s.Sync.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "time" {
				s.Time, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamSubscribeEvents_Sync.
var (
	jsonKey_JetstreamSubscribeEvents_Sync_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamSubscribeEvents_Sync_did         = []byte("\"did\":")
	jsonKey_JetstreamSubscribeEvents_Sync_seq         = []byte("\"seq\":")
	jsonKey_JetstreamSubscribeEvents_Sync_sync        = []byte("\"sync\":")
	jsonKey_JetstreamSubscribeEvents_Sync_time        = []byte("\"time\":")
)

func (s *JetstreamSubscribeEvents_Sync) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamSubscribeEvents_Sync) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamSubscribeEvents_Sync_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Sync_did...)
	buf = cbor.AppendJSONString(buf, s.DID)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Sync_seq...)
	buf = cbor.AppendJSONInt(buf, s.Seq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Sync_sync...)
	{
		var err error
		buf, err = s.Sync.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamSubscribeEvents_Sync_time...)
	buf = cbor.AppendJSONString(buf, s.Time)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamSubscribeEvents_Sync) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamSubscribeEvents_Sync) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "did":
			s.DID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "seq":
			s.Seq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "sync":
			pos, err = s.Sync.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		case "time":
			s.Time, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
