// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Error name constants for JetstreamGetImportStatus.
const (
	ErrJetstreamGetImportStatus_JobNotFound = "JobNotFound" // No import job matches the supplied id, or no job has ever run when the id is omitted.
)

// Precomputed JSON key tokens for JetstreamGetImportStatus_Output.
var (
	jsonKey_JetstreamGetImportStatus_Output_dollar_type            = []byte("\"$type\":")
	jsonKey_JetstreamGetImportStatus_Output_bucketed               = []byte("\"bucketed\":")
	jsonKey_JetstreamGetImportStatus_Output_error                  = []byte("\"error\":")
	jsonKey_JetstreamGetImportStatus_Output_finishedAt             = []byte("\"finishedAt\":")
	jsonKey_JetstreamGetImportStatus_Output_job                    = []byte("\"job\":")
	jsonKey_JetstreamGetImportStatus_Output_phase                  = []byte("\"phase\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsCorruptOffset      = []byte("\"rowsCorruptOffset\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsMatchedAllVersions = []byte("\"rowsMatchedAllVersions\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsMatchedSpecific    = []byte("\"rowsMatchedSpecific\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsMutated            = []byte("\"rowsMutated\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsRejected           = []byte("\"rowsRejected\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsTotal              = []byte("\"rowsTotal\":")
	jsonKey_JetstreamGetImportStatus_Output_rowsValid              = []byte("\"rowsValid\":")
	jsonKey_JetstreamGetImportStatus_Output_segmentsApplied        = []byte("\"segmentsApplied\":")
	jsonKey_JetstreamGetImportStatus_Output_segmentsExamined       = []byte("\"segmentsExamined\":")
	jsonKey_JetstreamGetImportStatus_Output_segmentsPatched        = []byte("\"segmentsPatched\":")
	jsonKey_JetstreamGetImportStatus_Output_segmentsToApply        = []byte("\"segmentsToApply\":")
	jsonKey_JetstreamGetImportStatus_Output_specificCidsUnmatched  = []byte("\"specificCidsUnmatched\":")
	jsonKey_JetstreamGetImportStatus_Output_state                  = []byte("\"state\":")
	jsonKey_JetstreamGetImportStatus_Output_submittedAt            = []byte("\"submittedAt\":")
)

func (s *JetstreamGetImportStatus_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamGetImportStatus_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Bucketed.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_bucketed...)
		buf = cbor.AppendJSONBool(buf, s.Bucketed.Val())
		first = false
	}
	if s.Error.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_error...)
		buf = cbor.AppendJSONString(buf, s.Error.Val())
		first = false
	}
	if s.FinishedAt.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_finishedAt...)
		buf = cbor.AppendJSONString(buf, s.FinishedAt.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_job...)
	buf = cbor.AppendJSONString(buf, s.Job)
	first = false
	if s.Phase.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_phase...)
		buf = cbor.AppendJSONString(buf, s.Phase.Val())
		first = false
	}
	if s.RowsCorruptOffset.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsCorruptOffset...)
		buf = cbor.AppendJSONInt(buf, s.RowsCorruptOffset.Val())
		first = false
	}
	if s.RowsMatchedAllVersions.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsMatchedAllVersions...)
		buf = cbor.AppendJSONInt(buf, s.RowsMatchedAllVersions.Val())
		first = false
	}
	if s.RowsMatchedSpecific.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsMatchedSpecific...)
		buf = cbor.AppendJSONInt(buf, s.RowsMatchedSpecific.Val())
		first = false
	}
	if s.RowsMutated.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsMutated...)
		buf = cbor.AppendJSONInt(buf, s.RowsMutated.Val())
		first = false
	}
	if s.RowsRejected.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsRejected...)
		buf = cbor.AppendJSONInt(buf, s.RowsRejected.Val())
		first = false
	}
	if s.RowsTotal.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsTotal...)
		buf = cbor.AppendJSONInt(buf, s.RowsTotal.Val())
		first = false
	}
	if s.RowsValid.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_rowsValid...)
		buf = cbor.AppendJSONInt(buf, s.RowsValid.Val())
		first = false
	}
	if s.SegmentsApplied.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_segmentsApplied...)
		buf = cbor.AppendJSONInt(buf, s.SegmentsApplied.Val())
		first = false
	}
	if s.SegmentsExamined.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_segmentsExamined...)
		buf = cbor.AppendJSONInt(buf, s.SegmentsExamined.Val())
		first = false
	}
	if s.SegmentsPatched.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_segmentsPatched...)
		buf = cbor.AppendJSONInt(buf, s.SegmentsPatched.Val())
		first = false
	}
	if s.SegmentsToApply.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_segmentsToApply...)
		buf = cbor.AppendJSONInt(buf, s.SegmentsToApply.Val())
		first = false
	}
	if s.SpecificCidsUnmatched.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_specificCidsUnmatched...)
		buf = cbor.AppendJSONInt(buf, s.SpecificCidsUnmatched.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_state...)
	buf = cbor.AppendJSONString(buf, s.State)
	first = false
	if s.SubmittedAt.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamGetImportStatus_Output_submittedAt...)
		buf = cbor.AppendJSONString(buf, s.SubmittedAt.Val())
		first = false
	}
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamGetImportStatus_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamGetImportStatus_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "bucketed":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v bool
				v, pos, err = cbor.ReadJSONBool(data, pos)
				if err != nil {
					return 0, err
				}
				s.Bucketed = gt.Some(v)
			}
		case "error":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Error = gt.Some(v)
			}
		case "finishedAt":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.FinishedAt = gt.Some(v)
			}
		case "job":
			s.Job, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "phase":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Phase = gt.Some(v)
			}
		case "rowsCorruptOffset":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsCorruptOffset = gt.Some(v)
			}
		case "rowsMatchedAllVersions":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsMatchedAllVersions = gt.Some(v)
			}
		case "rowsMatchedSpecific":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsMatchedSpecific = gt.Some(v)
			}
		case "rowsMutated":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsMutated = gt.Some(v)
			}
		case "rowsRejected":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsRejected = gt.Some(v)
			}
		case "rowsTotal":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsTotal = gt.Some(v)
			}
		case "rowsValid":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.RowsValid = gt.Some(v)
			}
		case "segmentsApplied":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.SegmentsApplied = gt.Some(v)
			}
		case "segmentsExamined":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.SegmentsExamined = gt.Some(v)
			}
		case "segmentsPatched":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.SegmentsPatched = gt.Some(v)
			}
		case "segmentsToApply":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.SegmentsToApply = gt.Some(v)
			}
		case "specificCidsUnmatched":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.SpecificCidsUnmatched = gt.Some(v)
			}
		case "state":
			s.State, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "submittedAt":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.SubmittedAt = gt.Some(v)
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamGetImportStatus_Output.
var (
	cborKey_JetstreamGetImportStatus_Output_job                    = cbor.AppendTextKey(nil, "job")
	cborKey_JetstreamGetImportStatus_Output_dollar_type            = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamGetImportStatus_Output_error                  = cbor.AppendTextKey(nil, "error")
	cborKey_JetstreamGetImportStatus_Output_phase                  = cbor.AppendTextKey(nil, "phase")
	cborKey_JetstreamGetImportStatus_Output_state                  = cbor.AppendTextKey(nil, "state")
	cborKey_JetstreamGetImportStatus_Output_bucketed               = cbor.AppendTextKey(nil, "bucketed")
	cborKey_JetstreamGetImportStatus_Output_rowsTotal              = cbor.AppendTextKey(nil, "rowsTotal")
	cborKey_JetstreamGetImportStatus_Output_rowsValid              = cbor.AppendTextKey(nil, "rowsValid")
	cborKey_JetstreamGetImportStatus_Output_finishedAt             = cbor.AppendTextKey(nil, "finishedAt")
	cborKey_JetstreamGetImportStatus_Output_rowsMutated            = cbor.AppendTextKey(nil, "rowsMutated")
	cborKey_JetstreamGetImportStatus_Output_submittedAt            = cbor.AppendTextKey(nil, "submittedAt")
	cborKey_JetstreamGetImportStatus_Output_rowsRejected           = cbor.AppendTextKey(nil, "rowsRejected")
	cborKey_JetstreamGetImportStatus_Output_segmentsApplied        = cbor.AppendTextKey(nil, "segmentsApplied")
	cborKey_JetstreamGetImportStatus_Output_segmentsPatched        = cbor.AppendTextKey(nil, "segmentsPatched")
	cborKey_JetstreamGetImportStatus_Output_segmentsToApply        = cbor.AppendTextKey(nil, "segmentsToApply")
	cborKey_JetstreamGetImportStatus_Output_segmentsExamined       = cbor.AppendTextKey(nil, "segmentsExamined")
	cborKey_JetstreamGetImportStatus_Output_rowsCorruptOffset      = cbor.AppendTextKey(nil, "rowsCorruptOffset")
	cborKey_JetstreamGetImportStatus_Output_rowsMatchedSpecific    = cbor.AppendTextKey(nil, "rowsMatchedSpecific")
	cborKey_JetstreamGetImportStatus_Output_specificCidsUnmatched  = cbor.AppendTextKey(nil, "specificCidsUnmatched")
	cborKey_JetstreamGetImportStatus_Output_rowsMatchedAllVersions = cbor.AppendTextKey(nil, "rowsMatchedAllVersions")
)

func (s *JetstreamGetImportStatus_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamGetImportStatus_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Error.HasVal() {
		n++
	}
	if s.Phase.HasVal() {
		n++
	}
	if s.Bucketed.HasVal() {
		n++
	}
	if s.RowsTotal.HasVal() {
		n++
	}
	if s.RowsValid.HasVal() {
		n++
	}
	if s.FinishedAt.HasVal() {
		n++
	}
	if s.RowsMutated.HasVal() {
		n++
	}
	if s.SubmittedAt.HasVal() {
		n++
	}
	if s.RowsRejected.HasVal() {
		n++
	}
	if s.SegmentsApplied.HasVal() {
		n++
	}
	if s.SegmentsPatched.HasVal() {
		n++
	}
	if s.SegmentsToApply.HasVal() {
		n++
	}
	if s.SegmentsExamined.HasVal() {
		n++
	}
	if s.RowsCorruptOffset.HasVal() {
		n++
	}
	if s.RowsMatchedSpecific.HasVal() {
		n++
	}
	if s.SpecificCidsUnmatched.HasVal() {
		n++
	}
	if s.RowsMatchedAllVersions.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "job", buf)
		buf = append(buf, cborKey_JetstreamGetImportStatus_Output_job...)
		buf = cbor.AppendText(buf, s.Job)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "error", buf)
		if s.Error.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_error...)
			buf = cbor.AppendText(buf, s.Error.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "phase", buf)
		if s.Phase.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_phase...)
			buf = cbor.AppendText(buf, s.Phase.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "state", buf)
		buf = append(buf, cborKey_JetstreamGetImportStatus_Output_state...)
		buf = cbor.AppendText(buf, s.State)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "bucketed", buf)
		if s.Bucketed.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_bucketed...)
			buf = cbor.AppendBool(buf, s.Bucketed.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsTotal", buf)
		if s.RowsTotal.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsTotal...)
			buf = cbor.AppendInt(buf, s.RowsTotal.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsValid", buf)
		if s.RowsValid.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsValid...)
			buf = cbor.AppendInt(buf, s.RowsValid.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "finishedAt", buf)
		if s.FinishedAt.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_finishedAt...)
			buf = cbor.AppendText(buf, s.FinishedAt.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsMutated", buf)
		if s.RowsMutated.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMutated...)
			buf = cbor.AppendInt(buf, s.RowsMutated.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "submittedAt", buf)
		if s.SubmittedAt.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_submittedAt...)
			buf = cbor.AppendText(buf, s.SubmittedAt.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsRejected", buf)
		if s.RowsRejected.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsRejected...)
			buf = cbor.AppendInt(buf, s.RowsRejected.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsApplied", buf)
		if s.SegmentsApplied.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsApplied...)
			buf = cbor.AppendInt(buf, s.SegmentsApplied.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsPatched", buf)
		if s.SegmentsPatched.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsPatched...)
			buf = cbor.AppendInt(buf, s.SegmentsPatched.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsToApply", buf)
		if s.SegmentsToApply.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsToApply...)
			buf = cbor.AppendInt(buf, s.SegmentsToApply.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsExamined", buf)
		if s.SegmentsExamined.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsExamined...)
			buf = cbor.AppendInt(buf, s.SegmentsExamined.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsCorruptOffset", buf)
		if s.RowsCorruptOffset.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsCorruptOffset...)
			buf = cbor.AppendInt(buf, s.RowsCorruptOffset.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsMatchedSpecific", buf)
		if s.RowsMatchedSpecific.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMatchedSpecific...)
			buf = cbor.AppendInt(buf, s.RowsMatchedSpecific.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "specificCidsUnmatched", buf)
		if s.SpecificCidsUnmatched.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_specificCidsUnmatched...)
			buf = cbor.AppendInt(buf, s.SpecificCidsUnmatched.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "rowsMatchedAllVersions", buf)
		if s.RowsMatchedAllVersions.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMatchedAllVersions...)
			buf = cbor.AppendInt(buf, s.RowsMatchedAllVersions.Val())
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamGetImportStatus_Output_job...)
		buf = cbor.AppendText(buf, s.Job)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Error.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_error...)
			buf = cbor.AppendText(buf, s.Error.Val())
		}
		if s.Phase.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_phase...)
			buf = cbor.AppendText(buf, s.Phase.Val())
		}
		buf = append(buf, cborKey_JetstreamGetImportStatus_Output_state...)
		buf = cbor.AppendText(buf, s.State)
		if s.Bucketed.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_bucketed...)
			buf = cbor.AppendBool(buf, s.Bucketed.Val())
		}
		if s.RowsTotal.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsTotal...)
			buf = cbor.AppendInt(buf, s.RowsTotal.Val())
		}
		if s.RowsValid.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsValid...)
			buf = cbor.AppendInt(buf, s.RowsValid.Val())
		}
		if s.FinishedAt.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_finishedAt...)
			buf = cbor.AppendText(buf, s.FinishedAt.Val())
		}
		if s.RowsMutated.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMutated...)
			buf = cbor.AppendInt(buf, s.RowsMutated.Val())
		}
		if s.SubmittedAt.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_submittedAt...)
			buf = cbor.AppendText(buf, s.SubmittedAt.Val())
		}
		if s.RowsRejected.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsRejected...)
			buf = cbor.AppendInt(buf, s.RowsRejected.Val())
		}
		if s.SegmentsApplied.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsApplied...)
			buf = cbor.AppendInt(buf, s.SegmentsApplied.Val())
		}
		if s.SegmentsPatched.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsPatched...)
			buf = cbor.AppendInt(buf, s.SegmentsPatched.Val())
		}
		if s.SegmentsToApply.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsToApply...)
			buf = cbor.AppendInt(buf, s.SegmentsToApply.Val())
		}
		if s.SegmentsExamined.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_segmentsExamined...)
			buf = cbor.AppendInt(buf, s.SegmentsExamined.Val())
		}
		if s.RowsCorruptOffset.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsCorruptOffset...)
			buf = cbor.AppendInt(buf, s.RowsCorruptOffset.Val())
		}
		if s.RowsMatchedSpecific.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMatchedSpecific...)
			buf = cbor.AppendInt(buf, s.RowsMatchedSpecific.Val())
		}
		if s.SpecificCidsUnmatched.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_specificCidsUnmatched...)
			buf = cbor.AppendInt(buf, s.SpecificCidsUnmatched.Val())
		}
		if s.RowsMatchedAllVersions.HasVal() {
			buf = append(buf, cborKey_JetstreamGetImportStatus_Output_rowsMatchedAllVersions...)
			buf = cbor.AppendInt(buf, s.RowsMatchedAllVersions.Val())
		}
	}
	return buf, nil
}

func (s *JetstreamGetImportStatus_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamGetImportStatus_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "job" {
				s.Job, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "error" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Error = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "phase" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Phase = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "state" {
				s.State, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "bucketed" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v bool
					v, pos, err = cbor.ReadBool(data, pos)
					if err != nil {
						return 0, err
					}
					s.Bucketed = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "rowsTotal" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsTotal = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "rowsValid" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsValid = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "finishedAt" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.FinishedAt = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "rowsMutated" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsMutated = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "submittedAt" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.SubmittedAt = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 12:
			if string(data[keyStart:keyEnd]) == "rowsRejected" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsRejected = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 15:
			if string(data[keyStart:keyEnd]) == "segmentsApplied" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.SegmentsApplied = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "segmentsPatched" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.SegmentsPatched = gt.Some(v)
				}
			} else if string(data[keyStart:keyEnd]) == "segmentsToApply" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.SegmentsToApply = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 16:
			if string(data[keyStart:keyEnd]) == "segmentsExamined" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.SegmentsExamined = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 17:
			if string(data[keyStart:keyEnd]) == "rowsCorruptOffset" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsCorruptOffset = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 19:
			if string(data[keyStart:keyEnd]) == "rowsMatchedSpecific" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsMatchedSpecific = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 21:
			if string(data[keyStart:keyEnd]) == "specificCidsUnmatched" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.SpecificCidsUnmatched = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 22:
			if string(data[keyStart:keyEnd]) == "rowsMatchedAllVersions" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.RowsMatchedAllVersions = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamGetImportStatus_Output struct {
	LexiconTypeID          string            `json:"$type,omitempty"`
	Bucketed               gt.Option[bool]   `json:"bucketed,omitzero"`   // Whether Phase A+B completed (the offset files are durable).
	Error                  gt.Option[string] `json:"error,omitzero"`      // Failure detail; present only when state is failed.
	FinishedAt             gt.Option[string] `json:"finishedAt,omitzero"` // Present only for a terminal job.
	Job                    string            `json:"job"`                 // Job id.
	Phase                  gt.Option[string] `json:"phase,omitzero"`      // Current phase: parse_bucket (Phase A+B) or apply (Phase C).
	RowsCorruptOffset      gt.Option[int64]  `json:"rowsCorruptOffset,omitzero"`
	RowsMatchedAllVersions gt.Option[int64]  `json:"rowsMatchedAllVersions,omitzero"`
	RowsMatchedSpecific    gt.Option[int64]  `json:"rowsMatchedSpecific,omitzero"`
	RowsMutated            gt.Option[int64]  `json:"rowsMutated,omitzero"`
	RowsRejected           gt.Option[int64]  `json:"rowsRejected,omitzero"`
	RowsTotal              gt.Option[int64]  `json:"rowsTotal,omitzero"`
	RowsValid              gt.Option[int64]  `json:"rowsValid,omitzero"`
	SegmentsApplied        gt.Option[int64]  `json:"segmentsApplied,omitzero"` // Segments processed so far in Phase C.
	SegmentsExamined       gt.Option[int64]  `json:"segmentsExamined,omitzero"`
	SegmentsPatched        gt.Option[int64]  `json:"segmentsPatched,omitzero"`
	SegmentsToApply        gt.Option[int64]  `json:"segmentsToApply,omitzero"` // Segments Phase C will process (after resume-skips).
	SpecificCidsUnmatched  gt.Option[int64]  `json:"specificCidsUnmatched,omitzero"`
	State                  string            `json:"state"` // Lifecycle state.
	SubmittedAt            gt.Option[string] `json:"submittedAt,omitzero"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// JetstreamGetImportStatus calls the XRPC query "network.bsky.jetstream.getImportStatus".
//
// Report the status of a timestamp-import job: lifecycle state, current phase, per-phase progress, and (on completion) the parse/mutation totals. With no job parameter, reports the current or most recent job. Bearer-token gated: without a configured token the endpoint always returns 401.
func JetstreamGetImportStatus(ctx context.Context, c *xrpc.Client, job string) (*JetstreamGetImportStatus_Output, error) {
	params := map[string]any{}
	if job != "" {
		params["job"] = job
	}
	var out JetstreamGetImportStatus_Output
	return &out, c.Query(ctx, "network.bsky.jetstream.getImportStatus", params, &out)
}
