// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// Precomputed JSON key tokens for JetstreamListSegments_Output.
var (
	jsonKey_JetstreamListSegments_Output_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamListSegments_Output_cursor      = []byte("\"cursor\":")
	jsonKey_JetstreamListSegments_Output_segments    = []byte("\"segments\":")
)

func (s *JetstreamListSegments_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamListSegments_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamListSegments_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.Cursor.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamListSegments_Output_cursor...)
		buf = cbor.AppendJSONString(buf, s.Cursor.Val())
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Output_segments...)
	buf = append(buf, '[')
	for i, item := range s.Segments {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamListSegments_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamListSegments_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "cursor":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v string
				v, pos, err = cbor.ReadJSONString(data, pos)
				if err != nil {
					return 0, err
				}
				s.Cursor = gt.Some(v)
			}
		case "segments":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Segments = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamListSegments_Segment
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Segments = append(s.Segments, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamListSegments_Output.
var (
	cborKey_JetstreamListSegments_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamListSegments_Output_cursor      = cbor.AppendTextKey(nil, "cursor")
	cborKey_JetstreamListSegments_Output_segments    = cbor.AppendTextKey(nil, "segments")
)

func (s *JetstreamListSegments_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamListSegments_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if s.Cursor.HasVal() {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamListSegments_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "cursor", buf)
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_JetstreamListSegments_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segments", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamListSegments_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if s.Cursor.HasVal() {
			buf = append(buf, cborKey_JetstreamListSegments_Output_cursor...)
			buf = cbor.AppendText(buf, s.Cursor.Val())
		}
		buf = append(buf, cborKey_JetstreamListSegments_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func (s *JetstreamListSegments_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamListSegments_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "cursor" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v string
					v, pos, err = cbor.ReadText(data, pos)
					if err != nil {
						return 0, err
					}
					s.Cursor = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "segments" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Segments = make([]JetstreamListSegments_Segment, arrLen)
					for idx := range arrLen {
						pos, err = s.Segments[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamListSegments_Output struct {
	LexiconTypeID string                          `json:"$type,omitempty"`
	Cursor        gt.Option[string]               `json:"cursor,omitzero"`
	Segments      []JetstreamListSegments_Segment `json:"segments"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// JetstreamListSegments calls the XRPC query "network.bsky.jetstream.listSegments".
//
// Enumerate sealed segment files available for download, in ascending index order.
func JetstreamListSegments(ctx context.Context, c *xrpc.Client, cursor string, limit int64) (*JetstreamListSegments_Output, error) {
	params := map[string]any{}
	if cursor != "" {
		params["cursor"] = cursor
	}
	if limit != 0 {
		params["limit"] = limit
	}
	var out JetstreamListSegments_Output
	return &out, c.Query(ctx, "network.bsky.jetstream.listSegments", params, &out)
}

// JetstreamListSegments_Segment is a "segment" in the network.bsky.jetstream.listSegments schema.
type JetstreamListSegments_Segment struct {
	LexiconTypeID  string `json:"$type,omitempty"`
	Checksum       string `json:"checksum"`   // Segment-format xxh3 metadata checksum as 16-char hex; equals the getSegment ETag.
	EventCount     int64  `json:"eventCount"` // Number of events in the segment.
	Index          int64  `json:"index"`      // Zero-based segment index.
	MaxSeq         int64  `json:"maxSeq"`
	MaxWitnessedAt int64  `json:"maxWitnessedAt"` // Latest witnessed-at, unix microseconds.
	MinSeq         int64  `json:"minSeq"`
	MinWitnessedAt int64  `json:"minWitnessedAt"` // Earliest witnessed-at, unix microseconds.
	Name           string `json:"name"`           // Segment filename; pass to getSegment.
	SizeBytes      int64  `json:"sizeBytes"`      // File size in bytes.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamListSegments_Segment.
var (
	cborKey_JetstreamListSegments_Segment_name           = cbor.AppendTextKey(nil, "name")
	cborKey_JetstreamListSegments_Segment_dollar_type    = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamListSegments_Segment_index          = cbor.AppendTextKey(nil, "index")
	cborKey_JetstreamListSegments_Segment_maxSeq         = cbor.AppendTextKey(nil, "maxSeq")
	cborKey_JetstreamListSegments_Segment_minSeq         = cbor.AppendTextKey(nil, "minSeq")
	cborKey_JetstreamListSegments_Segment_checksum       = cbor.AppendTextKey(nil, "checksum")
	cborKey_JetstreamListSegments_Segment_sizeBytes      = cbor.AppendTextKey(nil, "sizeBytes")
	cborKey_JetstreamListSegments_Segment_eventCount     = cbor.AppendTextKey(nil, "eventCount")
	cborKey_JetstreamListSegments_Segment_maxWitnessedAt = cbor.AppendTextKey(nil, "maxWitnessedAt")
	cborKey_JetstreamListSegments_Segment_minWitnessedAt = cbor.AppendTextKey(nil, "minWitnessedAt")
)

func (s *JetstreamListSegments_Segment) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamListSegments_Segment) AppendCBOR(buf []byte) ([]byte, error) {
	n := 9 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "name", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamListSegments_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "index", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "maxSeq", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "minSeq", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "checksum", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "sizeBytes", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_sizeBytes...)
		buf = cbor.AppendInt(buf, s.SizeBytes)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "eventCount", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_eventCount...)
		buf = cbor.AppendInt(buf, s.EventCount)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "maxWitnessedAt", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_maxWitnessedAt...)
		buf = cbor.AppendInt(buf, s.MaxWitnessedAt)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "minWitnessedAt", buf)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_minWitnessedAt...)
		buf = cbor.AppendInt(buf, s.MinWitnessedAt)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamListSegments_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamListSegments_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamListSegments_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_sizeBytes...)
		buf = cbor.AppendInt(buf, s.SizeBytes)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_eventCount...)
		buf = cbor.AppendInt(buf, s.EventCount)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_maxWitnessedAt...)
		buf = cbor.AppendInt(buf, s.MaxWitnessedAt)
		buf = append(buf, cborKey_JetstreamListSegments_Segment_minWitnessedAt...)
		buf = cbor.AppendInt(buf, s.MinWitnessedAt)
	}
	return buf, nil
}

func (s *JetstreamListSegments_Segment) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamListSegments_Segment) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "index" {
				s.Index, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "maxSeq" {
				s.MaxSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "minSeq" {
				s.MinSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "checksum" {
				s.Checksum, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "sizeBytes" {
				s.SizeBytes, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 10:
			if string(data[keyStart:keyEnd]) == "eventCount" {
				s.EventCount, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 14:
			if string(data[keyStart:keyEnd]) == "maxWitnessedAt" {
				s.MaxWitnessedAt, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "minWitnessedAt" {
				s.MinWitnessedAt, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamListSegments_Segment.
var (
	jsonKey_JetstreamListSegments_Segment_dollar_type    = []byte("\"$type\":")
	jsonKey_JetstreamListSegments_Segment_checksum       = []byte("\"checksum\":")
	jsonKey_JetstreamListSegments_Segment_eventCount     = []byte("\"eventCount\":")
	jsonKey_JetstreamListSegments_Segment_index          = []byte("\"index\":")
	jsonKey_JetstreamListSegments_Segment_maxSeq         = []byte("\"maxSeq\":")
	jsonKey_JetstreamListSegments_Segment_maxWitnessedAt = []byte("\"maxWitnessedAt\":")
	jsonKey_JetstreamListSegments_Segment_minSeq         = []byte("\"minSeq\":")
	jsonKey_JetstreamListSegments_Segment_minWitnessedAt = []byte("\"minWitnessedAt\":")
	jsonKey_JetstreamListSegments_Segment_name           = []byte("\"name\":")
	jsonKey_JetstreamListSegments_Segment_sizeBytes      = []byte("\"sizeBytes\":")
)

func (s *JetstreamListSegments_Segment) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamListSegments_Segment) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamListSegments_Segment_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_checksum...)
	buf = cbor.AppendJSONString(buf, s.Checksum)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_eventCount...)
	buf = cbor.AppendJSONInt(buf, s.EventCount)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_index...)
	buf = cbor.AppendJSONInt(buf, s.Index)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_maxSeq...)
	buf = cbor.AppendJSONInt(buf, s.MaxSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_maxWitnessedAt...)
	buf = cbor.AppendJSONInt(buf, s.MaxWitnessedAt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_minSeq...)
	buf = cbor.AppendJSONInt(buf, s.MinSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_minWitnessedAt...)
	buf = cbor.AppendJSONInt(buf, s.MinWitnessedAt)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamListSegments_Segment_sizeBytes...)
	buf = cbor.AppendJSONInt(buf, s.SizeBytes)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamListSegments_Segment) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamListSegments_Segment) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "checksum":
			s.Checksum, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "eventCount":
			s.EventCount, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "index":
			s.Index, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "maxSeq":
			s.MaxSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "maxWitnessedAt":
			s.MaxWitnessedAt, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "minSeq":
			s.MinSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "minWitnessedAt":
			s.MinWitnessedAt, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "sizeBytes":
			s.SizeBytes, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
