// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
	"github.com/jcalabro/gt"
)

// JetstreamPlanSnapshot_BlockRange is a "blockRange" in the network.bsky.jetstream.planSnapshot schema.
type JetstreamPlanSnapshot_BlockRange struct {
	LexiconTypeID string `json:"$type,omitempty"`
	First         int64  `json:"first"` // Index of the first block in the range.
	Last          int64  `json:"last"`  // Index of the last block in the range.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanSnapshot_BlockRange.
var (
	cborKey_JetstreamPlanSnapshot_BlockRange_last        = cbor.AppendTextKey(nil, "last")
	cborKey_JetstreamPlanSnapshot_BlockRange_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanSnapshot_BlockRange_first       = cbor.AppendTextKey(nil, "first")
)

func (s *JetstreamPlanSnapshot_BlockRange) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_BlockRange) AppendCBOR(buf []byte) ([]byte, error) {
	n := 2 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "last", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_last...)
		buf = cbor.AppendInt(buf, s.Last)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "first", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_first...)
		buf = cbor.AppendInt(buf, s.First)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_last...)
		buf = cbor.AppendInt(buf, s.Last)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_BlockRange_first...)
		buf = cbor.AppendInt(buf, s.First)
	}
	return buf, nil
}

func (s *JetstreamPlanSnapshot_BlockRange) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_BlockRange) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "last" {
				s.Last, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "first" {
				s.First, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanSnapshot_BlockRange.
var (
	jsonKey_JetstreamPlanSnapshot_BlockRange_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanSnapshot_BlockRange_first       = []byte("\"first\":")
	jsonKey_JetstreamPlanSnapshot_BlockRange_last        = []byte("\"last\":")
)

func (s *JetstreamPlanSnapshot_BlockRange) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_BlockRange) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_BlockRange_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_BlockRange_first...)
	buf = cbor.AppendJSONInt(buf, s.First)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_BlockRange_last...)
	buf = cbor.AppendJSONInt(buf, s.Last)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanSnapshot_BlockRange) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_BlockRange) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "first":
			s.First, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "last":
			s.Last, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed JSON key tokens for JetstreamPlanSnapshot_Output.
var (
	jsonKey_JetstreamPlanSnapshot_Output_dollar_type       = []byte("\"$type\":")
	jsonKey_JetstreamPlanSnapshot_Output_plannedThroughSeq = []byte("\"plannedThroughSeq\":")
	jsonKey_JetstreamPlanSnapshot_Output_sealedTipSeq      = []byte("\"sealedTipSeq\":")
	jsonKey_JetstreamPlanSnapshot_Output_segments          = []byte("\"segments\":")
	jsonKey_JetstreamPlanSnapshot_Output_stats             = []byte("\"stats\":")
)

func (s *JetstreamPlanSnapshot_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Output_plannedThroughSeq...)
	buf = cbor.AppendJSONInt(buf, s.PlannedThroughSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Output_sealedTipSeq...)
	buf = cbor.AppendJSONInt(buf, s.SealedTipSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Output_segments...)
	buf = append(buf, '[')
	for i, item := range s.Segments {
		if i > 0 {
			buf = append(buf, ',')
		}
		var err error
		buf, err = item.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	buf = append(buf, ']')
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Output_stats...)
	{
		var err error
		buf, err = s.Stats.AppendJSON(buf)
		if err != nil {
			return nil, err
		}
	}
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "plannedThroughSeq":
			s.PlannedThroughSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "sealedTipSeq":
			s.SealedTipSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segments":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Segments = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamPlanSnapshot_Segment
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Segments = append(s.Segments, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "stats":
			pos, err = s.Stats.UnmarshalJSONAt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamPlanSnapshot_Output.
var (
	cborKey_JetstreamPlanSnapshot_Output_dollar_type       = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanSnapshot_Output_stats             = cbor.AppendTextKey(nil, "stats")
	cborKey_JetstreamPlanSnapshot_Output_segments          = cbor.AppendTextKey(nil, "segments")
	cborKey_JetstreamPlanSnapshot_Output_sealedTipSeq      = cbor.AppendTextKey(nil, "sealedTipSeq")
	cborKey_JetstreamPlanSnapshot_Output_plannedThroughSeq = cbor.AppendTextKey(nil, "plannedThroughSeq")
)

func (s *JetstreamPlanSnapshot_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "stats", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_stats...)
		{
			var err error
			buf, err = s.Stats.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segments", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "sealedTipSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_sealedTipSeq...)
		buf = cbor.AppendInt(buf, s.SealedTipSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "plannedThroughSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_plannedThroughSeq...)
		buf = cbor.AppendInt(buf, s.PlannedThroughSeq)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_stats...)
		{
			var err error
			buf, err = s.Stats.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_segments...)
		buf = cbor.AppendArrayHeader(buf, uint64(len(s.Segments)))
		for _, item := range s.Segments {
			var err error
			buf, err = item.AppendCBOR(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_sealedTipSeq...)
		buf = cbor.AppendInt(buf, s.SealedTipSeq)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Output_plannedThroughSeq...)
		buf = cbor.AppendInt(buf, s.PlannedThroughSeq)
	}
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "stats" {
				pos, err = s.Stats.UnmarshalCBORAt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "segments" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Segments = make([]JetstreamPlanSnapshot_Segment, arrLen)
					for idx := range arrLen {
						pos, err = s.Segments[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 12:
			if string(data[keyStart:keyEnd]) == "sealedTipSeq" {
				s.SealedTipSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 17:
			if string(data[keyStart:keyEnd]) == "plannedThroughSeq" {
				s.PlannedThroughSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamPlanSnapshot_Output struct {
	LexiconTypeID     string                          `json:"$type,omitempty"`
	PlannedThroughSeq int64                           `json:"plannedThroughSeq"` // The last sealed sequence covered by this page. Use this value as afterSeq for the next page. If t...
	SealedTipSeq      int64                           `json:"sealedTipSeq"`      // The end of the sealed archive for this snapshot, capped by beforeSeq when provided. Use this valu...
	Segments          []JetstreamPlanSnapshot_Segment `json:"segments"`
	Stats             JetstreamPlanSnapshot_Stats     `json:"stats"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed JSON key tokens for JetstreamPlanSnapshot_Input.
var (
	jsonKey_JetstreamPlanSnapshot_Input_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanSnapshot_Input_afterSeq    = []byte("\"afterSeq\":")
	jsonKey_JetstreamPlanSnapshot_Input_beforeSeq   = []byte("\"beforeSeq\":")
	jsonKey_JetstreamPlanSnapshot_Input_collections = []byte("\"collections\":")
	jsonKey_JetstreamPlanSnapshot_Input_dids        = []byte("\"dids\":")
	jsonKey_JetstreamPlanSnapshot_Input_kinds       = []byte("\"kinds\":")
)

func (s *JetstreamPlanSnapshot_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if s.AfterSeq.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_afterSeq...)
		buf = cbor.AppendJSONInt(buf, s.AfterSeq.Val())
		first = false
	}
	if s.BeforeSeq.HasVal() {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_beforeSeq...)
		buf = cbor.AppendJSONInt(buf, s.BeforeSeq.Val())
		first = false
	}
	if len(s.Collections) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_collections...)
		buf = append(buf, '[')
		for i, item := range s.Collections {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.Dids) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_dids...)
		buf = append(buf, '[')
		for i, item := range s.Dids {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	if len(s.Kinds) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Input_kinds...)
		buf = append(buf, '[')
		for i, item := range s.Kinds {
			if i > 0 {
				buf = append(buf, ',')
			}
			buf = cbor.AppendJSONString(buf, item)
		}
		buf = append(buf, ']')
		first = false
	}
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "afterSeq":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.AfterSeq = gt.Some(v)
			}
		case "beforeSeq":
			if cbor.IsJSONNull(data, pos) {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				var v int64
				v, pos, err = cbor.ReadJSONInt(data, pos)
				if err != nil {
					return 0, err
				}
				s.BeforeSeq = gt.Some(v)
			}
		case "collections":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Collections = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Collections = append(s.Collections, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "dids":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Dids = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Dids = append(s.Dids, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "kinds":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Kinds = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem string
					elem, pos, err = cbor.ReadJSONString(data, pos)
					if err != nil {
						return 0, err
					}
					s.Kinds = append(s.Kinds, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamPlanSnapshot_Input.
var (
	cborKey_JetstreamPlanSnapshot_Input_dids        = cbor.AppendTextKey(nil, "dids")
	cborKey_JetstreamPlanSnapshot_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanSnapshot_Input_kinds       = cbor.AppendTextKey(nil, "kinds")
	cborKey_JetstreamPlanSnapshot_Input_afterSeq    = cbor.AppendTextKey(nil, "afterSeq")
	cborKey_JetstreamPlanSnapshot_Input_beforeSeq   = cbor.AppendTextKey(nil, "beforeSeq")
	cborKey_JetstreamPlanSnapshot_Input_collections = cbor.AppendTextKey(nil, "collections")
)

func (s *JetstreamPlanSnapshot_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 0 + countExtra(s.extra, extraEncodingCBOR)
	if len(s.Dids) > 0 {
		n++
	}
	if s.LexiconTypeID != "" {
		n++
	}
	if len(s.Kinds) > 0 {
		n++
	}
	if s.AfterSeq.HasVal() {
		n++
	}
	if s.BeforeSeq.HasVal() {
		n++
	}
	if len(s.Collections) > 0 {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "dids", buf)
		if len(s.Dids) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_dids...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Dids)))
			for _, item := range s.Dids {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "kinds", buf)
		if len(s.Kinds) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_kinds...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Kinds)))
			for _, item := range s.Kinds {
				buf = cbor.AppendText(buf, item)
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "afterSeq", buf)
		if s.AfterSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_afterSeq...)
			buf = cbor.AppendInt(buf, s.AfterSeq.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "beforeSeq", buf)
		if s.BeforeSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_beforeSeq...)
			buf = cbor.AppendInt(buf, s.BeforeSeq.Val())
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "collections", buf)
		if len(s.Collections) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_collections...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Collections)))
			for _, item := range s.Collections {
				buf = cbor.AppendText(buf, item)
			}
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if len(s.Dids) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_dids...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Dids)))
			for _, item := range s.Dids {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		if len(s.Kinds) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_kinds...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Kinds)))
			for _, item := range s.Kinds {
				buf = cbor.AppendText(buf, item)
			}
		}
		if s.AfterSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_afterSeq...)
			buf = cbor.AppendInt(buf, s.AfterSeq.Val())
		}
		if s.BeforeSeq.HasVal() {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_beforeSeq...)
			buf = cbor.AppendInt(buf, s.BeforeSeq.Val())
		}
		if len(s.Collections) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Input_collections...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Collections)))
			for _, item := range s.Collections {
				buf = cbor.AppendText(buf, item)
			}
		}
	}
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "dids" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Dids = make([]string, arrLen)
					for idx := range arrLen {
						s.Dids[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "kinds" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Kinds = make([]string, arrLen)
					for idx := range arrLen {
						s.Kinds[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "afterSeq" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.AfterSeq = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 9:
			if string(data[keyStart:keyEnd]) == "beforeSeq" {
				if cbor.IsNull(data, pos) {
					pos++
				} else {
					var v int64
					v, pos, err = cbor.ReadInt(data, pos)
					if err != nil {
						return 0, err
					}
					s.BeforeSeq = gt.Some(v)
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 11:
			if string(data[keyStart:keyEnd]) == "collections" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Collections = make([]string, arrLen)
					for idx := range arrLen {
						s.Collections[idx], pos, err = cbor.ReadText(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamPlanSnapshot_Input struct {
	LexiconTypeID string           `json:"$type,omitempty"`
	AfterSeq      gt.Option[int64] `json:"afterSeq,omitzero"`     // Start after this sequence number. Events at or below it are not included.
	BeforeSeq     gt.Option[int64] `json:"beforeSeq,omitzero"`    // Stop at this sequence number. Events above it are not included.
	Collections   []string         `json:"collections,omitempty"` // Collection NSIDs or namespace wildcards such as app.bsky.feed.*; constrains commit events only. N...
	Dids          []string         `json:"dids,omitempty"`        // Only include data for these DIDs. Omit this field or pass an empty array to include all DIDs.
	Kinds         []string         `json:"kinds,omitempty"`       // Event kinds to include. Omit this field or pass an empty array to include all kinds.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// JetstreamPlanSnapshot calls the XRPC procedure "network.bsky.jetstream.planSnapshot".
//
// Build a download plan for the desired data pattern. The plan lists whole segments or block ranges that might contain events for the requested kinds, DIDs, and collections.
func JetstreamPlanSnapshot(ctx context.Context, c *xrpc.Client, input *JetstreamPlanSnapshot_Input) (*JetstreamPlanSnapshot_Output, error) {
	var out JetstreamPlanSnapshot_Output
	return &out, c.Procedure(ctx, "network.bsky.jetstream.planSnapshot", input, &out)
}

// JetstreamPlanSnapshot_Segment is a "segment" in the network.bsky.jetstream.planSnapshot schema.
type JetstreamPlanSnapshot_Segment struct {
	LexiconTypeID string                             `json:"$type,omitempty"`
	Blocks        []JetstreamPlanSnapshot_BlockRange `json:"blocks,omitempty"` // Block ranges to download, including both endpoints. This field is present only when mode is blocks.
	Checksum      string                             `json:"checksum"`         // The segment's xxh3 metadata checksum, encoded as 16 hexadecimal characters.
	Index         int64                              `json:"index"`            // Zero-based segment index.
	MaxSeq        int64                              `json:"maxSeq"`
	MinSeq        int64                              `json:"minSeq"`
	Mode          string                             `json:"mode"` // How to download this segment. For segment, download the whole file with getSegment. For blocks, d...
	Name          string                             `json:"name"` // Segment filename to pass to getSegment or getBlock.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanSnapshot_Segment.
var (
	cborKey_JetstreamPlanSnapshot_Segment_mode        = cbor.AppendTextKey(nil, "mode")
	cborKey_JetstreamPlanSnapshot_Segment_name        = cbor.AppendTextKey(nil, "name")
	cborKey_JetstreamPlanSnapshot_Segment_dollar_type = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanSnapshot_Segment_index       = cbor.AppendTextKey(nil, "index")
	cborKey_JetstreamPlanSnapshot_Segment_blocks      = cbor.AppendTextKey(nil, "blocks")
	cborKey_JetstreamPlanSnapshot_Segment_maxSeq      = cbor.AppendTextKey(nil, "maxSeq")
	cborKey_JetstreamPlanSnapshot_Segment_minSeq      = cbor.AppendTextKey(nil, "minSeq")
	cborKey_JetstreamPlanSnapshot_Segment_checksum    = cbor.AppendTextKey(nil, "checksum")
)

func (s *JetstreamPlanSnapshot_Segment) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Segment) AppendCBOR(buf []byte) ([]byte, error) {
	n := 6 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	if len(s.Blocks) > 0 {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "mode", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_mode...)
		buf = cbor.AppendText(buf, s.Mode)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "name", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "index", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "blocks", buf)
		if len(s.Blocks) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_blocks...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Blocks)))
			for _, item := range s.Blocks {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "maxSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "minSeq", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "checksum", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_mode...)
		buf = cbor.AppendText(buf, s.Mode)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_name...)
		buf = cbor.AppendText(buf, s.Name)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_index...)
		buf = cbor.AppendInt(buf, s.Index)
		if len(s.Blocks) > 0 {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_blocks...)
			buf = cbor.AppendArrayHeader(buf, uint64(len(s.Blocks)))
			for _, item := range s.Blocks {
				var err error
				buf, err = item.AppendCBOR(buf)
				if err != nil {
					return nil, err
				}
			}
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_maxSeq...)
		buf = cbor.AppendInt(buf, s.MaxSeq)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_minSeq...)
		buf = cbor.AppendInt(buf, s.MinSeq)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Segment_checksum...)
		buf = cbor.AppendText(buf, s.Checksum)
	}
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Segment) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Segment) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "mode" {
				s.Mode, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "name" {
				s.Name, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "index" {
				s.Index, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 6:
			if string(data[keyStart:keyEnd]) == "blocks" {
				{
					arrLen, newPos, err := cbor.ReadArrayHeader(data, pos)
					if err != nil {
						return 0, err
					}
					if err := cbor.CheckArrayLen(arrLen, data, newPos); err != nil {
						return 0, err
					}
					pos = newPos
					s.Blocks = make([]JetstreamPlanSnapshot_BlockRange, arrLen)
					for idx := range arrLen {
						pos, err = s.Blocks[idx].UnmarshalCBORAt(data, pos)
						if err != nil {
							return 0, err
						}
					}
				}
			} else if string(data[keyStart:keyEnd]) == "maxSeq" {
				s.MaxSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else if string(data[keyStart:keyEnd]) == "minSeq" {
				s.MinSeq, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 8:
			if string(data[keyStart:keyEnd]) == "checksum" {
				s.Checksum, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanSnapshot_Segment.
var (
	jsonKey_JetstreamPlanSnapshot_Segment_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamPlanSnapshot_Segment_blocks      = []byte("\"blocks\":")
	jsonKey_JetstreamPlanSnapshot_Segment_checksum    = []byte("\"checksum\":")
	jsonKey_JetstreamPlanSnapshot_Segment_index       = []byte("\"index\":")
	jsonKey_JetstreamPlanSnapshot_Segment_maxSeq      = []byte("\"maxSeq\":")
	jsonKey_JetstreamPlanSnapshot_Segment_minSeq      = []byte("\"minSeq\":")
	jsonKey_JetstreamPlanSnapshot_Segment_mode        = []byte("\"mode\":")
	jsonKey_JetstreamPlanSnapshot_Segment_name        = []byte("\"name\":")
)

func (s *JetstreamPlanSnapshot_Segment) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Segment) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if len(s.Blocks) > 0 {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_blocks...)
		buf = append(buf, '[')
		for i, item := range s.Blocks {
			if i > 0 {
				buf = append(buf, ',')
			}
			var err error
			buf, err = item.AppendJSON(buf)
			if err != nil {
				return nil, err
			}
		}
		buf = append(buf, ']')
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_checksum...)
	buf = cbor.AppendJSONString(buf, s.Checksum)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_index...)
	buf = cbor.AppendJSONInt(buf, s.Index)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_maxSeq...)
	buf = cbor.AppendJSONInt(buf, s.MaxSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_minSeq...)
	buf = cbor.AppendJSONInt(buf, s.MinSeq)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_mode...)
	buf = cbor.AppendJSONString(buf, s.Mode)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Segment_name...)
	buf = cbor.AppendJSONString(buf, s.Name)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Segment) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Segment) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "blocks":
			if !cbor.IsJSONNull(data, pos) {
				pos, err = cbor.ReadJSONArrayStart(data, pos)
				if err != nil {
					return 0, err
				}
				s.Blocks = nil
				for {
					var done bool
					pos, done = cbor.ReadJSONArrayEnd(data, pos)
					if done {
						break
					}
					var elem JetstreamPlanSnapshot_BlockRange
					pos, err = elem.UnmarshalJSONAt(data, pos)
					if err != nil {
						return 0, err
					}
					s.Blocks = append(s.Blocks, elem)
					pos = cbor.SkipJSONComma(data, pos)
				}
			} else {
				pos, err = cbor.SkipJSONNull(data, pos)
				if err != nil {
					return 0, err
				}
			}
		case "checksum":
			s.Checksum, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "index":
			s.Index, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "maxSeq":
			s.MaxSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "minSeq":
			s.MinSeq, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "mode":
			s.Mode, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "name":
			s.Name, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// JetstreamPlanSnapshot_Stats is a "stats" in the network.bsky.jetstream.planSnapshot schema.
type JetstreamPlanSnapshot_Stats struct {
	LexiconTypeID    string `json:"$type,omitempty"`
	BlocksMatched    int64  `json:"blocksMatched"`
	Entries          int64  `json:"entries"` // Number of items counted toward the server's per-page plan limit.
	SegmentsExamined int64  `json:"segmentsExamined"`
	SegmentsMatched  int64  `json:"segmentsMatched"`

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed CBOR key tokens for JetstreamPlanSnapshot_Stats.
var (
	cborKey_JetstreamPlanSnapshot_Stats_dollar_type      = cbor.AppendTextKey(nil, "$type")
	cborKey_JetstreamPlanSnapshot_Stats_entries          = cbor.AppendTextKey(nil, "entries")
	cborKey_JetstreamPlanSnapshot_Stats_blocksMatched    = cbor.AppendTextKey(nil, "blocksMatched")
	cborKey_JetstreamPlanSnapshot_Stats_segmentsMatched  = cbor.AppendTextKey(nil, "segmentsMatched")
	cborKey_JetstreamPlanSnapshot_Stats_segmentsExamined = cbor.AppendTextKey(nil, "segmentsExamined")
)

func (s *JetstreamPlanSnapshot_Stats) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Stats) AppendCBOR(buf []byte) ([]byte, error) {
	n := 4 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "entries", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_entries...)
		buf = cbor.AppendInt(buf, s.Entries)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "blocksMatched", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_blocksMatched...)
		buf = cbor.AppendInt(buf, s.BlocksMatched)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsMatched", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_segmentsMatched...)
		buf = cbor.AppendInt(buf, s.SegmentsMatched)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "segmentsExamined", buf)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_segmentsExamined...)
		buf = cbor.AppendInt(buf, s.SegmentsExamined)
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_entries...)
		buf = cbor.AppendInt(buf, s.Entries)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_blocksMatched...)
		buf = cbor.AppendInt(buf, s.BlocksMatched)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_segmentsMatched...)
		buf = cbor.AppendInt(buf, s.SegmentsMatched)
		buf = append(buf, cborKey_JetstreamPlanSnapshot_Stats_segmentsExamined...)
		buf = cbor.AppendInt(buf, s.SegmentsExamined)
	}
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Stats) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Stats) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 7:
			if string(data[keyStart:keyEnd]) == "entries" {
				s.Entries, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 13:
			if string(data[keyStart:keyEnd]) == "blocksMatched" {
				s.BlocksMatched, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 15:
			if string(data[keyStart:keyEnd]) == "segmentsMatched" {
				s.SegmentsMatched, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 16:
			if string(data[keyStart:keyEnd]) == "segmentsExamined" {
				s.SegmentsExamined, pos, err = cbor.ReadInt(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

// Precomputed JSON key tokens for JetstreamPlanSnapshot_Stats.
var (
	jsonKey_JetstreamPlanSnapshot_Stats_dollar_type      = []byte("\"$type\":")
	jsonKey_JetstreamPlanSnapshot_Stats_blocksMatched    = []byte("\"blocksMatched\":")
	jsonKey_JetstreamPlanSnapshot_Stats_entries          = []byte("\"entries\":")
	jsonKey_JetstreamPlanSnapshot_Stats_segmentsExamined = []byte("\"segmentsExamined\":")
	jsonKey_JetstreamPlanSnapshot_Stats_segmentsMatched  = []byte("\"segmentsMatched\":")
)

func (s *JetstreamPlanSnapshot_Stats) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamPlanSnapshot_Stats) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamPlanSnapshot_Stats_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Stats_blocksMatched...)
	buf = cbor.AppendJSONInt(buf, s.BlocksMatched)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Stats_entries...)
	buf = cbor.AppendJSONInt(buf, s.Entries)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Stats_segmentsExamined...)
	buf = cbor.AppendJSONInt(buf, s.SegmentsExamined)
	first = false
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamPlanSnapshot_Stats_segmentsMatched...)
	buf = cbor.AppendJSONInt(buf, s.SegmentsMatched)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamPlanSnapshot_Stats) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamPlanSnapshot_Stats) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "blocksMatched":
			s.BlocksMatched, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "entries":
			s.Entries, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segmentsExamined":
			s.SegmentsExamined, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		case "segmentsMatched":
			s.SegmentsMatched, pos, err = cbor.ReadJSONInt(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}
