// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for JetstreamGetSegment.
const (
	ErrJetstreamGetSegment_SegmentNotFound = "SegmentNotFound"
)

// JetstreamGetSegment calls the XRPC query "network.bsky.jetstream.getSegment".
//
// Download a sealed segment file by name.
func JetstreamGetSegment(ctx context.Context, c *xrpc.Client, name string) ([]byte, error) {
	params := map[string]any{}
	params["name"] = name
	return c.QueryRaw(ctx, "network.bsky.jetstream.getSegment", params)
}
