// Code generated by lexgen. DO NOT EDIT.

package jetstream

import (
	"context"
	"github.com/jcalabro/atmos/cbor"
	"github.com/jcalabro/atmos/xrpc"
)

// Error name constants for JetstreamImportTimestamps.
const (
	ErrJetstreamImportTimestamps_ImportInProgress = "ImportInProgress" // Another import job is already running; only one runs at a time.
	ErrJetstreamImportTimestamps_ImportNotReady   = "ImportNotReady"   // Timestamp import requires the server to be in steady state with the live writer running.
	ErrJetstreamImportTimestamps_InvalidPath      = "InvalidPath"      // The path is empty, escapes the import directory, does not exist, or is not a regular file.
)

// Precomputed JSON key tokens for JetstreamImportTimestamps_Output.
var (
	jsonKey_JetstreamImportTimestamps_Output_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamImportTimestamps_Output_job         = []byte("\"job\":")
)

func (s *JetstreamImportTimestamps_Output) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamImportTimestamps_Output) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamImportTimestamps_Output_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamImportTimestamps_Output_job...)
	buf = cbor.AppendJSONString(buf, s.Job)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamImportTimestamps_Output) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamImportTimestamps_Output) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "job":
			s.Job, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamImportTimestamps_Output.
var (
	cborKey_JetstreamImportTimestamps_Output_job         = cbor.AppendTextKey(nil, "job")
	cborKey_JetstreamImportTimestamps_Output_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *JetstreamImportTimestamps_Output) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamImportTimestamps_Output) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "job", buf)
		buf = append(buf, cborKey_JetstreamImportTimestamps_Output_job...)
		buf = cbor.AppendText(buf, s.Job)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamImportTimestamps_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamImportTimestamps_Output_job...)
		buf = cbor.AppendText(buf, s.Job)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamImportTimestamps_Output_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *JetstreamImportTimestamps_Output) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamImportTimestamps_Output) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 3:
			if string(data[keyStart:keyEnd]) == "job" {
				s.Job, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamImportTimestamps_Output struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Job           string `json:"job"` // Opaque job id. Poll getImportStatus with this id to observe progress and the terminal result.

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// Precomputed JSON key tokens for JetstreamImportTimestamps_Input.
var (
	jsonKey_JetstreamImportTimestamps_Input_dollar_type = []byte("\"$type\":")
	jsonKey_JetstreamImportTimestamps_Input_path        = []byte("\"path\":")
)

func (s *JetstreamImportTimestamps_Input) MarshalJSON() ([]byte, error) {
	return s.AppendJSON(make([]byte, 0, 256))
}

func (s *JetstreamImportTimestamps_Input) AppendJSON(buf []byte) ([]byte, error) {
	buf = append(buf, '{')
	first := true
	if s.LexiconTypeID != "" {
		if !first {
			buf = append(buf, ',')
		}
		buf = append(buf, jsonKey_JetstreamImportTimestamps_Input_dollar_type...)
		buf = cbor.AppendJSONString(buf, s.LexiconTypeID)
		first = false
	}
	if !first {
		buf = append(buf, ',')
	}
	buf = append(buf, jsonKey_JetstreamImportTimestamps_Input_path...)
	buf = cbor.AppendJSONString(buf, s.Path)
	first = false
	for _, ef := range s.extra {
		if ef.Encoding != extraEncodingJSON {
			continue
		}
		if !first {
			buf = append(buf, ',')
		}
		buf = cbor.AppendJSONString(buf, ef.Key)
		buf = append(buf, ':')
		buf = append(buf, ef.Value...)
		first = false
	}
	buf = append(buf, '}')
	return buf, nil
}

func (s *JetstreamImportTimestamps_Input) UnmarshalJSON(data []byte) error {
	_, err := s.UnmarshalJSONAt(data, 0)
	return err
}

func (s *JetstreamImportTimestamps_Input) UnmarshalJSONAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingJSON)
	var err error
	pos, err = cbor.ReadJSONObjectStart(data, pos)
	if err != nil {
		return 0, err
	}
	for {
		var done bool
		pos, done = cbor.ReadJSONObjectEnd(data, pos)
		if done {
			return pos, nil
		}
		var key string
		key, pos, err = cbor.ReadJSONKey(data, pos)
		if err != nil {
			return 0, err
		}
		switch key {
		case "$type":
			s.LexiconTypeID, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		case "path":
			s.Path, pos, err = cbor.ReadJSONString(data, pos)
			if err != nil {
				return 0, err
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipJSONValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: key, Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingJSON})
		}
		pos = cbor.SkipJSONComma(data, pos)
	}
}

// Precomputed CBOR key tokens for JetstreamImportTimestamps_Input.
var (
	cborKey_JetstreamImportTimestamps_Input_path        = cbor.AppendTextKey(nil, "path")
	cborKey_JetstreamImportTimestamps_Input_dollar_type = cbor.AppendTextKey(nil, "$type")
)

func (s *JetstreamImportTimestamps_Input) MarshalCBOR() ([]byte, error) {
	return s.AppendCBOR(make([]byte, 0, 256))
}

func (s *JetstreamImportTimestamps_Input) AppendCBOR(buf []byte) ([]byte, error) {
	n := 1 + countExtra(s.extra, extraEncodingCBOR)
	if s.LexiconTypeID != "" {
		n++
	}
	buf = cbor.AppendMapHeader(buf, uint64(n))
	if len(s.extra) > 0 {
		ei := 0
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "path", buf)
		buf = append(buf, cborKey_JetstreamImportTimestamps_Input_path...)
		buf = cbor.AppendText(buf, s.Path)
		ei, buf = appendCBORExtrasBefore(s.extra, ei, "$type", buf)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamImportTimestamps_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
		_, buf = appendCBORExtrasBefore(s.extra, ei, "", buf)
	} else {
		buf = append(buf, cborKey_JetstreamImportTimestamps_Input_path...)
		buf = cbor.AppendText(buf, s.Path)
		if s.LexiconTypeID != "" {
			buf = append(buf, cborKey_JetstreamImportTimestamps_Input_dollar_type...)
			buf = cbor.AppendText(buf, s.LexiconTypeID)
		}
	}
	return buf, nil
}

func (s *JetstreamImportTimestamps_Input) UnmarshalCBOR(data []byte) error {
	_, err := s.UnmarshalCBORAt(data, 0)
	return err
}

func (s *JetstreamImportTimestamps_Input) UnmarshalCBORAt(data []byte, pos int) (int, error) {
	s.extra = clearExtra(s.extra, extraEncodingCBOR)
	count, pos, err := cbor.ReadMapHeader(data, pos)
	if err != nil {
		return 0, err
	}
	for i := uint64(0); i < count; i++ {
		keyStart, keyEnd, newPos, err := cbor.ReadTextKey(data, pos)
		if err != nil {
			return 0, err
		}
		pos = newPos
		switch keyEnd - keyStart {
		case 4:
			if string(data[keyStart:keyEnd]) == "path" {
				s.Path, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		case 5:
			if string(data[keyStart:keyEnd]) == "$type" {
				s.LexiconTypeID, pos, err = cbor.ReadText(data, pos)
				if err != nil {
					return 0, err
				}
			} else {
				valueStart := pos
				pos, err = cbor.SkipValue(data, pos)
				if err != nil {
					return 0, err
				}
				s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
			}
		default:
			valueStart := pos
			pos, err = cbor.SkipValue(data, pos)
			if err != nil {
				return 0, err
			}
			s.extra = append(s.extra, extraField{Key: string(data[keyStart:keyEnd]), Value: append([]byte(nil), data[valueStart:pos]...), Encoding: extraEncodingCBOR})
		}
	}
	return pos, nil
}

type JetstreamImportTimestamps_Input struct {
	LexiconTypeID string `json:"$type,omitempty"`
	Path          string `json:"path"` // Server-local path to the plain (uncompressed) import CSV, resolved within the configured import d...

	// extra preserves unknown fields for same-format round-trips.
	extra []extraField
}

// JetstreamImportTimestamps calls the XRPC procedure "network.bsky.jetstream.importTimestamps".
//
// Submit a timestamp-import job. The referenced CSV is staged server-local out-of-band and named by a path confined to the server's configured import directory (paths escaping it via .. or a symlink are rejected). The job runs asynchronously and shares the segment-rewrite lock with delete-compaction, so only one import runs at a time; a concurrent submit is rejected. Bearer-token gated: without a configured token the endpoint always returns 401.
func JetstreamImportTimestamps(ctx context.Context, c *xrpc.Client, input *JetstreamImportTimestamps_Input) (*JetstreamImportTimestamps_Output, error) {
	var out JetstreamImportTimestamps_Output
	return &out, c.Procedure(ctx, "network.bsky.jetstream.importTimestamps", input, &out)
}
