#!/usr/bin/env python3
"""Generate the bundled collection seed from a clean hypercerts-lexicon checkout."""

import argparse
import json
from pathlib import Path
import subprocess


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("checkout", type=Path)
    args = parser.parse_args()
    root = args.checkout.resolve()
    if subprocess.check_output(["git", "-C", str(root), "status", "--porcelain"]):
        parser.error("the lexicon checkout must be clean so its commit identifies the seed")
    revision = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()
    collections = set()
    for path in sorted((root / "lexicons").rglob("*.json")):
        lexicon = json.loads(path.read_text())
        nsid = lexicon.get("id", "")
        if nsid.startswith(("org.hypercerts.", "app.certified.")) and (
            lexicon.get("defs", {}).get("main", {}).get("type") == "record"
        ):
            collections.add(nsid)
    if not collections:
        parser.error("no Hypercerts/Certified record lexicons found")
    target = Path(__file__).resolve().parents[1] / (
        "jetstream/internal/hypercerts/selection/defaults.go"
    )
    lines = [
        "// Code generated by scripts/update-collection-seed.py; DO NOT EDIT.",
        "// Source: hypercerts-org/hypercerts-lexicon at " + revision,
        "package selection",
        "",
        "// DefaultCollections returns the bundled Hypercerts/Certified record NSIDs.",
        "// Each call returns its own slice; administrator edits never mutate the seed.",
        "func DefaultCollections() []string {",
        "\treturn []string{",
        *("\t\t" + json.dumps(nsid) + "," for nsid in sorted(collections)),
        "\t}",
        "}",
        "",
    ]
    target.write_text("\n".join(lines))
    print(f"Wrote {len(collections)} collections from {revision} to {target}")


if __name__ == "__main__":
    main()
