// Code generated by scripts/update-collection-seed.py; DO NOT EDIT.
// Source: hypercerts-org/hypercerts-lexicon at 645177d67752834ae0e8a2876c118489b50c0a50
package selection

// DefaultCollections returns the bundled Hypercerts/Certified record NSIDs.
// Each call returns its own slice; administrator edits never mutate the seed.
func DefaultCollections() []string {
	return []string{
		"app.certified.actor.organization",
		"app.certified.actor.profile",
		"app.certified.badge.award",
		"app.certified.badge.definition",
		"app.certified.badge.response",
		"app.certified.graph.entityFollow",
		"app.certified.graph.follow",
		"app.certified.link.evm",
		"app.certified.location",
		"app.certified.signature.proof",
		"org.hypercerts.claim.activity",
		"org.hypercerts.claim.contribution",
		"org.hypercerts.claim.contributorInformation",
		"org.hypercerts.claim.rights",
		"org.hypercerts.collection",
		"org.hypercerts.context.acknowledgement",
		"org.hypercerts.context.attachment",
		"org.hypercerts.context.evaluation",
		"org.hypercerts.context.measurement",
		"org.hypercerts.funding.receipt",
		"org.hypercerts.workscope.tag",
	}
}
